#!/bin/sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

rm -rf ${SCRIPT_DIR}/html
rm -rf ${SCRIPT_DIR}/docset
rm -rf ${SCRIPT_DIR}/publish

appledoc \
  \
  --keep-intermediate-files \
  --no-create-docset \
  --no-install-docset \
  --keep-undocumented-objects \
  --keep-undocumented-members \
  --no-repeat-first-par \
  --no-warn-undocumented-object \
  --no-warn-undocumented-member \
  --explicit-crossref \
  --keep-merged-sections \
  \
  --project-name    BBHotpotato \
  --project-company BiasedBit \
  --company-id      com.biasedbit \
  --ignore          .m \
  --index-desc      ${SCRIPT_DIR}/index.md \
  --output          ${SCRIPT_DIR} \
  \
  ${SCRIPT_DIR}/../Classes
